DROP TABLE CARD_INFO CASCADE CONSTRAINTS;

CREATE TABLE PLASTIC
(
  ID                  NUMBER(18)                NOT NULL,
  ACNT_CONTRACT__OID  NUMBER(18),
  CARD_SUBTYPE        NUMBER(18),
  SERVICE_CODE        VARCHAR2(32 CHAR),
  CARD_NUMBER         VARCHAR2(64 CHAR),
  CARD_EXPIRE         VARCHAR2(4 CHAR),
  CARD_NAME           VARCHAR2(32 CHAR),
  COMPANY_NAME        VARCHAR2(32 CHAR),
  SEQV_NUMBER         VARCHAR2(32 CHAR),
  PRODUCTION_TYPE     VARCHAR2(1 CHAR),
  PRODUCTION_EVENT    VARCHAR2(32 CHAR),
  CHIP_SCHEME         NUMBER(18),
  ORDER_FROM          VARCHAR2(32 CHAR),
  ORDER_TO            VARCHAR2(32 CHAR),
  ORDER_N             VARCHAR2(64 CHAR),
  PIN                 VARCHAR2(32 CHAR),
  PM_PARMS            NUMBER(18),
  PIN_FORMAT          VARCHAR2(32 CHAR),
  PVV                 VARCHAR2(32 CHAR),
  CVC                 VARCHAR2(32 CHAR),
  PRODUCTION_CODE     NUMBER(3)                 DEFAULT 0                     NOT NULL,
  PROD_DATE           DATE,
  DATE_FROM           DATE,
  EVENT               VARCHAR2(1 CHAR),
  CVC2                VARCHAR2(32 CHAR),
  ICVV                VARCHAR2(32 CHAR),
  PREV_CARD           NUMBER(18),
  PARENT_CARD         NUMBER(18),
  OFFSET_DATA         VARCHAR2(32 CHAR),
  LIMIT_CURR          VARCHAR2(3 CHAR),
  PM_CODE             VARCHAR2(32 CHAR),
  STATUS              VARCHAR2(1 CHAR),
  CARD_TRACK_1        VARCHAR2(32 CHAR),
  ADD_TRACK_DATA      VARCHAR2(32 CHAR),
  COMMENT_TEXT        VARCHAR2(255 CHAR),
  TRANS_STATUS        VARCHAR2(1 CHAR),
  FILE_INFO__ID       NUMBER(18),
  EXT_DATA            VARCHAR2(3900 CHAR),
  ATC                 VARCHAR2(32 CHAR),
  SUBTYPE_CODE        VARCHAR2(32 CHAR),
  OFFL_PIN            VARCHAR2(1 CHAR),
  ROUTING_IDT         VARCHAR2(32 CHAR),
  APPLY_DT            DATE,
  LOCAL_VERSION       NUMBER(9)                 DEFAULT 0                     NOT NULL,
  REMOTE_VERSION      NUMBER(9)                 DEFAULT 0                     NOT NULL
)
TABLESPACE OWCONTR_D
PCTUSED    0
PCTFREE    15
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      KEEP
           )
LOGGING 
NOCOMPRESS 
CACHE;


CREATE UNIQUE INDEX CARD_INFO2 ON CARD_INFO
(ACNT_CONTRACT__OID, CARD_EXPIRE, STATUS, ID)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      KEEP
           );
CREATE UNIQUE INDEX PK_CARD_INFO ON CARD_INFO
(ID)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CARD_INFO ADD (
  CONSTRAINT PK_CARD_INFO
  PRIMARY KEY
  (ID)
  USING INDEX PK_CARD_INFO
  ENABLE VALIDATE);


CREATE INDEX CARD_BY_NUMBER ON CARD_INFO
(CARD_NUMBER)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX CARD_INFO1 ON CARD_INFO
(FILE_INFO__ID, ACNT_CONTRACT__OID)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX CARD_PARENT ON CARD_INFO
(PARENT_CARD)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX CARD_STATUS ON CARD_INFO
(STATUS, PROD_DATE)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

DROP SEQUENCE CARD_INFO_SEQ;

CREATE SEQUENCE CARD_INFO_SEQ
  START WITH 57790
  INCREMENT BY 10
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE OR REPLACE TRIGGER CARD_INFO_TIBS
  BEFORE INSERT ON CARD_INFO
  for each row
begin
  IF :new.ID IS NULL THEN
    if oracle_trgsupp.EnabledTo is null or sysdate >= oracle_trgsupp.EnabledTo then
      oracle_trgsupp.CHECK_ENABLED ('CARD_INFO');
    end if;
    SELECT CARD_INFO_SEQ.NEXTVAL INTO :new.ID FROM DUAL;
    oracle_trgsupp.LastId := :new.ID;
  END IF;
end;
/


ALTER TABLE CARD_INFO ADD (
  CONSTRAINT FK_ACNT_C__CARD_IN 
  FOREIGN KEY (ACNT_CONTRACT__OID) 
  REFERENCES ACNT_CONTRACT (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

GRANT UPDATE ON CARD_INFO TO MAFCR1;

GRANT SELECT, UPDATE ON CARD_INFO TO MAFCR1130;

GRANT SELECT ON CARD_INFO TO MAFCR1130U;

GRANT SELECT, UPDATE ON CARD_INFO TO MAFCR1730;

GRANT SELECT ON CARD_INFO TO MAFCR1730U;

GRANT SELECT ON CARD_INFO TO MAFCROWN;

GRANT SELECT ON CARD_INFO TO MAFCRSEL;

GRANT SELECT ON CARD_INFO TO MAFCRTS;
