-- Phase 1
create schema cs;

CREATE TABLE CLIENT
(
  STATE          VARCHAR(10),
  DATE_CREATED           DATE,
  ID                  int NOT NULL,
  BRANCH              VARCHAR(32),
  CLIENT_CAT          VARCHAR(20),
  PRODUCT_CAT         VARCHAR(20),
  CLIENT_NAME          VARCHAR(255),
  BIRTH_DATE          DATE,
  GENDER              VARCHAR(1),
  CLIENT_NUMBER       VARCHAR(64),
  REG_NUMBER          VARCHAR(64),
  ADDRESS_LINE        VARCHAR(255),
  PHONE               VARCHAR(32),
  FAX                 VARCHAR(32),
  E_MAIL              VARCHAR(255),
  ADD_DATE            DATE,
  ADD_INFO            VARCHAR(3900),
  IS_READY            VARCHAR(1)          DEFAULT 'N',
  PRIMARY KEY (ID)
);


CREATE TABLE ADDRESS
(
  STATE          VARCHAR(1),
  DATE_CREATED           DATE,
  ID                  INT                NOT NULL,
  CLIENT__ID          INT,
  ADDRESS_TYPE        VARCHAR(255),
  ADDRESS_LINE        VARCHAR(255),
  ZIP_CODE            VARCHAR(32),
  PHONE               VARCHAR(32),
  E_MAIL              VARCHAR(255),
  URL                 VARCHAR(255),
  DELIVERY_TYPE       VARCHAR(255),
  IS_READY            VARCHAR(1),
  PRIMARY KEY (ID),
  FOREIGN KEY (CLIENT__ID) REFERENCES CLIENT(ID)
);

CREATE TABLE CONTRACT
(
  STATE               VARCHAR(10),
  ID                  INT                NOT NULL,
  PRODUCT_CAT                VARCHAR(10),
  CON_CAT             VARCHAR(10),
  CONTRACT_NUMBER     VARCHAR(64),
  COMMENT_TEXT        VARCHAR(255),
  MAIN_PRODUCT        VARCHAR(255),
  CLIENT__ID          INT,
  CURR                VARCHAR(3),
  AMOUNT_AVAILABLE    INT,
  DATE_OPEN           DATE,
  DATE_EXPIRE         DATE,
  CARD_EXPIRE         VARCHAR(4),
  CONTR_STATUS        VARCHAR(255),
  ADD_INFO            VARCHAR(255),
  IS_READY            VARCHAR(1),
  PRIMARY KEY (ID),
  FOREIGN KEY (CLIENT__ID) REFERENCES CLIENT(ID)
);

INSERT INTO CLIENT (STATE, DATE_CREATED, ID, BRANCH, CLIENT_CAT, PRODUCT_CAT, CLIENT_NAME, BIRTH_DATE, GENDER, CLIENT_NUMBER, REG_NUMBER, ADDRESS_LINE, PHONE, FAX, E_MAIL, ADD_DATE, ADD_INFO, IS_READY) 
VALUES ('A', '2022-05-16', 100, 'HCM', 'PRIVATE', 'ISS', 'NG DUY', '1992-05-16', 'M', '100', '100', '', '0930991111', '9999', 'duyng@gmail.com', null, null, 'Y');

INSERT INTO CLIENT (STATE, DATE_CREATED, ID, BRANCH, CLIENT_CAT, PRODUCT_CAT, CLIENT_NAME, BIRTH_DATE, GENDER, CLIENT_NUMBER, REG_NUMBER, ADDRESS_LINE, PHONE, FAX, E_MAIL, ADD_DATE, ADD_INFO, IS_READY) 
VALUES ('A', '2022-05-16', 200, 'HN', 'COMMERCIAL', 'ACQ', 'NG HAO', '1982-05-16', 'M', '200', '200', '', '09309112221', '3333', 'hao@gmail.com', null, null, 'Y');

INSERT INTO CLIENT (STATE, DATE_CREATED, ID, BRANCH, CLIENT_CAT, PRODUCT_CAT, CLIENT_NAME, BIRTH_DATE, GENDER, CLIENT_NUMBER, REG_NUMBER, ADDRESS_LINE, PHONE, FAX, E_MAIL, ADD_DATE, ADD_INFO, IS_READY) 
VALUES ('A', '2022-05-16', 300, 'HN', 'COMMERCIAL', 'ACQ', 'NG SAN', '1977-05-16', 'F', '300', '300', '', '09309112221', '4444', 'san@gmail.com', null, null, 'Y');

INSERT INTO CONTRACT (STATE, ID, PRODUCT_CAT, CON_CAT, CONTRACT_NUMBER, COMMENT_TEXT, MAIN_PRODUCT, CLIENT__ID, CURR, AMOUNT_AVAILABLE, DATE_OPEN, DATE_EXPIRE, CARD_EXPIRE, CONTR_STATUS, ADD_INFO, IS_READY) 
VALUES ('A', 100, 'ISS', 'CARD', '6250941006528599', '', 'CHINA UNION', 100, 'VND', 10000, '2022-05-16', '2025-02-09', '2901', 'Card OK', '', 'Y');

INSERT INTO CONTRACT (STATE, ID, PRODUCT_CAT, CON_CAT, CONTRACT_NUMBER, COMMENT_TEXT, MAIN_PRODUCT, CLIENT__ID, CURR, AMOUNT_AVAILABLE, DATE_OPEN, DATE_EXPIRE, CARD_EXPIRE, CONTR_STATUS, ADD_INFO, IS_READY) 
VALUES ('A', 200, 'ISS', 'CARD', '378282246310005', '', 'Amex', 200, 'VND', 51000, '2022-05-16', '2025-02-09', '2901', 'Card OK', '', 'Y');

INSERT INTO CONTRACT (STATE, ID, PRODUCT_CAT, CON_CAT, CONTRACT_NUMBER, COMMENT_TEXT, MAIN_PRODUCT, CLIENT__ID, CURR, AMOUNT_AVAILABLE, DATE_OPEN, DATE_EXPIRE, CARD_EXPIRE, CONTR_STATUS, ADD_INFO, IS_READY) 
VALUES ('A', 300, 'ISS', 'CARD', '378282246310005', '', 'Amex', 300, 'VND', 511000, '2022-05-16', '2025-02-09', '2901', 'Card OK', '', 'Y');

INSERT INTO ADDRESS (STATE, DATE_CREATED, ID, CLIENT__ID, ADDRESS_TYPE, ADDRESS_LINE, ZIP_CODE, PHONE, E_MAIL, URL, DELIVERY_TYPE, IS_READY) 
VALUES ('A', '2022-05-16', 100, 100, 'PERSONAL HOME', '123 Le Van Viet', '700000', '090385881', 'duyng@gmail.com', 'duyshinnosuke@gmail.com', 'COD', 'Y');

INSERT INTO ADDRESS (STATE, DATE_CREATED, ID, CLIENT__ID, ADDRESS_TYPE, ADDRESS_LINE, ZIP_CODE, PHONE, E_MAIL, URL, DELIVERY_TYPE, IS_READY) 
VALUES ('A', '2022-05-16', 200, 200, 'WORKPLACE', '72 Le Thanh Ton', '700000', '099876626', 'hao@gmail.com', 'hao@gmail.com', 'COD', 'Y');

INSERT INTO ADDRESS (STATE, DATE_CREATED, ID, CLIENT__ID, ADDRESS_TYPE, ADDRESS_LINE, ZIP_CODE, PHONE, E_MAIL, URL, DELIVERY_TYPE, IS_READY) 
VALUES ('A', '2022-05-16', 300, 300, 'WORKPLACE', '12 Phan Dang Luu', '700000', '098877222', 'phan@gmail.com', 'phan@gmail.com', 'COD', 'Y');

-- Phase 2
CREATE TABLE PLASTIC
(
  ID                  INT                NOT NULL,
  ACNT_CONTRACT__OID  INT,
  CARD_SUBTYPE        INT,
  CARD_NUMBER         VARCHAR2(64),
  CARD_EXPIRE         VARCHAR2(4),
  PRODUCTION_EVENT    VARCHAR2(32),
  PIN_FORMAT          VARCHAR2(32),
  PVV                 VARCHAR2(32),
  CVC                 VARCHAR2(32),
  CVC2                VARCHAR2(32),
);

CREATE TABLE STATUS
(
  STATE             VARCHAR(1),
  DATE_CREATED      DATE,
  ID                INT,
  NAME              VARCHAR2(255),
  CODE              VARCHAR2(2)
);
