DROP TABLE CLIENT_ADDRESS CASCADE CONSTRAINTS;




CREATE TABLE ADDRESS
(
  STATE          VARCHAR(1),
  DATE_CREATED           DATE,
  ID                  INT                NOT NULL,
  CLIENT__OID         INT,
  ADDRESS_TYPE        VARCHAR(255),
  ADDRESS_LINE        VARCHAR(255),
  ZIP_CODE            VARCHAR(32),
  PHONE               VARCHAR(32),
  E_MAIL              VARCHAR(255),
  URL                 VARCHAR(255),
  DELIVERY_TYPE       VARCHAR(255),
  IS_READY            VARCHAR(1)
);

INSERT INTO cs.ADDRESS (STATE, DATE_CREATED, ID, CLIENT__OID, ADDRESS_TYPE, ADDRESS_LINE, ZIP_CODE, PHONE, E_MAIL, URL, DELIVERY_TYPE, IS_READY) VALUES ('A', '2022-05-16', 100, 100, 'PERSONAL HOME', '123 Le Van Viet', '700000', '090385881', 'duyng@gmail.com', 'duyshinnosuke@gmail.com', 'COD', 'Y');
INSERT INTO cs.ADDRESS (STATE, DATE_CREATED, ID, CLIENT__OID, ADDRESS_TYPE, ADDRESS_LINE, ZIP_CODE, PHONE, E_MAIL, URL, DELIVERY_TYPE, IS_READY) VALUES ('A', '2022-05-16', 200, 200, 'WORKPLACE', '72 Le Thanh Ton', '700000', '099876626', 'hao@gmail.com', 'hao@gmail.com', 'COD', 'Y');
INSERT INTO cs.ADDRESS (STATE, DATE_CREATED, ID, CLIENT__OID, ADDRESS_TYPE, ADDRESS_LINE, ZIP_CODE, PHONE, E_MAIL, URL, DELIVERY_TYPE, IS_READY) VALUES ('A', '2022-05-16', 300, 300, 'WORKPLACE', '12 Phan Dang Luu', '700000', '098877222', 'phan@gmail.com', 'phan@gmail.com', 'COD', 'Y');


TABLESPACE OWCONTR_D
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX CLIENT_ADDRESS1 ON CLIENT_ADDRESS
(CLIENT__OID, AMND_STATE, ADDRESS_TYPE, IS_ACTIVE, ID)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX CLIENT_ADDRESS2 ON CLIENT_ADDRESS
(ACNT_CONTRACT__OID, AMND_STATE, ADDRESS_TYPE, IS_ACTIVE, ID)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX CLIENT_ADDRESS_ZIP ON CLIENT_ADDRESS
(ADDRESS_ZIP, ADDRESS_TYPE, IS_ACTIVE, AMND_STATE, ID, 
ACNT_CONTRACT__OID, CLIENT__OID)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX PK_CLIENT_ADDRESS ON CLIENT_ADDRESS
(ID)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE CLIENT_ADDRESS ADD (
  CONSTRAINT PK_CLIENT_ADDRESS
  PRIMARY KEY
  (ID)
  USING INDEX PK_CLIENT_ADDRESS
  ENABLE VALIDATE);


CREATE INDEX IP_CLIENT_ADDRESS ON CLIENT_ADDRESS
(AMND_PREV)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PARENT_ADDRESS ON CLIENT_ADDRESS
(PARENT_ADDRESS)
LOGGING
TABLESPACE OWCONTR_I
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

DROP SEQUENCE CLIENT_ADDRESS_SEQ;

CREATE SEQUENCE CLIENT_ADDRESS_SEQ
  START WITH 176200
  INCREMENT BY 10
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER
  NOKEEP
  NOSCALE
  GLOBAL;


CREATE OR REPLACE TRIGGER CLIENT_ADDRESS_TIBS
  BEFORE INSERT ON CLIENT_ADDRESS
  for each row
begin
  IF :new.ID IS NULL THEN
    if oracle_trgsupp.EnabledTo is null or sysdate >= oracle_trgsupp.EnabledTo then
      oracle_trgsupp.CHECK_ENABLED ('CLIENT_ADDRESS');
    end if;
    SELECT CLIENT_ADDRESS_SEQ.NEXTVAL INTO :new.ID FROM DUAL;
    oracle_trgsupp.LastId := :new.ID;
  END IF;
  IF :new.amnd_prev IS NULL THEN
    :new.amnd_prev := :new.ID;
  END IF;
  IF :new.amnd_officer IS NULL OR :new.amnd_officer = 0 THEN
    :new.amnd_officer := oracle_trgsupp.OfficerId;
  END IF;
end;
/


ALTER TABLE CLIENT_ADDRESS ADD (
  CONSTRAINT FK_CLIENT__ADDRESS 
  FOREIGN KEY (CLIENT__OID) 
  REFERENCES CLIENT (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE
,  CONSTRAINT FK_CONTRACT__ADDRE 
  FOREIGN KEY (ACNT_CONTRACT__OID) 
  REFERENCES ACNT_CONTRACT (ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);

GRANT DELETE, INSERT, UPDATE ON CLIENT_ADDRESS TO MAFCR1;

GRANT DELETE, INSERT, SELECT, UPDATE ON CLIENT_ADDRESS TO MAFCR1130;

GRANT SELECT ON CLIENT_ADDRESS TO MAFCR1130U;

GRANT DELETE, INSERT, SELECT, UPDATE ON CLIENT_ADDRESS TO MAFCR1730;

GRANT SELECT ON CLIENT_ADDRESS TO MAFCR1730U;

GRANT INSERT, SELECT, UPDATE ON CLIENT_ADDRESS TO MAFCROWN;

GRANT SELECT ON CLIENT_ADDRESS TO MAFCRSEL;

GRANT SELECT ON CLIENT_ADDRESS TO MAFCRW4CS;
